//! Installs so-context into OpenCode's global config.
//!
//! Writes:
//!   - MCP server entry in `~/.config/opencode/opencode.json`
//!   - Plugin file at `~/.config/opencode/plugins/so-context.js`
//!
//! The plugin subscribes to `session.created` and `session.deleted` events to
//! call `so-context ensure-watch` / `so-context unwatch` with the session ID
//! and project directory, giving the daemon accurate per-session consumer
//! tracking including the OpenCode session ID as agent identity.

use anyhow::{Context, Result};
use serde_json::{Map, Value};
use std::fs;
use std::path::PathBuf;

const SERVER_NAME: &str = "so-context";

pub fn config_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_default();
    PathBuf::from(home).join(".config").join("opencode")
}

pub fn config_path() -> PathBuf {
    config_dir().join("opencode.json")
}

pub fn plugin_path() -> PathBuf {
    config_dir().join("plugins").join("so-context.js")
}

pub fn install(binary: &str) -> Result<()> {
    install_mcp(binary)?;
    install_plugin(binary)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// MCP server entry
// ---------------------------------------------------------------------------

fn install_mcp(binary: &str) -> Result<()> {
    let path = config_path();
    fs::create_dir_all(path.parent().unwrap())
        .with_context(|| format!("create dir {}", path.parent().unwrap().display()))?;

    let mut root: Value = if path.exists() {
        let text = fs::read_to_string(&path)
            .with_context(|| format!("read {}", path.display()))?;
        serde_json::from_str(&text).unwrap_or(Value::Object(Map::new()))
    } else {
        Value::Object(Map::new())
    };

    let mcp = root
        .as_object_mut()
        .unwrap()
        .entry("mcp")
        .or_insert(Value::Object(Map::new()))
        .as_object_mut()
        .unwrap();

    mcp.insert(
        SERVER_NAME.to_string(),
        serde_json::json!({
            "type": "local",
            "command": [binary, "mcp"],
            "enabled": true
        }),
    );

    let text = serde_json::to_string_pretty(&root)?;
    fs::write(&path, text).with_context(|| format!("write {}", path.display()))?;
    println!("OpenCode: wrote MCP entry to {}", path.display());
    Ok(())
}

// ---------------------------------------------------------------------------
// Plugin file
// ---------------------------------------------------------------------------

/// Generates the JavaScript plugin source for a given binary path.
fn plugin_source(binary: &str) -> String {
    // Escape the binary path for embedding in a JS string literal.
    let bin = binary.replace('\\', "\\\\").replace('"', "\\\"");

    format!(
        r#"// so-context OpenCode plugin — auto-generated by `so-context setup`
// Tracks project watch sessions: calls ensure-watch on session start and
// unwatch on session end, passing the OpenCode session ID so the daemon can
// maintain an accurate per-session consumer list.

export const SoContextPlugin = async ({{ directory }}) => {{
  const binary = "{bin}";

  return {{
    event: async ({{ event }}) => {{
      if (event.type === "session.created") {{
        const sessionId = event.properties?.sessionID ?? event.properties?.id ?? "opencode";
        const dir = directory ?? ".";
        await Bun.$`${{binary}} ensure-watch ${{dir}} --agent-id ${{sessionId}}`.nothrow().quiet();
      }}

      if (event.type === "session.deleted") {{
        const sessionId = event.properties?.sessionID ?? event.properties?.id ?? "opencode";
        const dir = directory ?? ".";
        await Bun.$`${{binary}} unwatch ${{dir}} --agent-id ${{sessionId}}`.nothrow().quiet();
      }}
    }},
  }};
}};
"#
    )
}

fn install_plugin(binary: &str) -> Result<()> {
    let path = plugin_path();
    fs::create_dir_all(path.parent().unwrap())
        .with_context(|| format!("create dir {}", path.parent().unwrap().display()))?;

    let source = plugin_source(binary);
    fs::write(&path, source).with_context(|| format!("write {}", path.display()))?;
    println!("OpenCode: wrote plugin to {}", path.display());
    Ok(())
}
