// so-context OpenCode plugin — auto-generated by `so-context setup`
// Tracks project watch sessions: calls ensure-watch on session start and
// unwatch on session end, passing the OpenCode session ID so the daemon can
// maintain an accurate per-session consumer list.
//
// Event shape (from opencode/src/session/session.ts):
//   session.created / session.deleted
//     properties.sessionID  — the session identifier
//     properties.info       — full Session.Info object
//     properties.info.directory — the session's working directory

export const SoContextPlugin = async ({ directory: projectDir, $ }) => {
  const binary = "{BINARY}";

  return {
    event: async ({ event }) => {
      if (event.type === "session.created" || event.type === "session.deleted") {
        const sessionId = event.properties?.sessionID ?? "opencode";
        // Prefer the session's own directory over the plugin context directory.
        const dir = event.properties?.info?.directory ?? projectDir ?? ".";
        const cmd = event.type === "session.created" ? "ensure-watch" : "unwatch";
        await $`${binary} ${cmd} ${dir} --agent-id ${sessionId}`.nothrow().quiet();
      }
    },
  };
};
