// so-context OpenCode plugin — auto-generated by `so-context setup`
//
// Injects the agent session ID into every so-context MCP tool call before it
// reaches the daemon, so the daemon can attribute events to the correct
// context window (sub-agent).
//
// Watch lifecycle is handled automatically by the daemon via the MCP
// connection: projects are registered on initialize and unwatched on
// connection close. No session lifecycle hooks are needed.
//
// Hook: tool.execute.before
//   input.tool     — tool name, e.g. "so-context_so_read"
//   input.sessionID — the calling context window's session ID
//   output.args    — the tool arguments object (mutated in place)
//
// OpenCode registers MCP tools as "<server-name>_<tool-name>", so tools from
// the "so-context" MCP server are prefixed with "so-context_".

import type { Plugin } from "@opencode-ai/plugin";

export const SoContextPlugin: Plugin = async () => {
  return {
    "tool.execute.before": async (input, output) => {
      // Only intercept so-context MCP tools.
      if (!input.tool.startsWith("so-context_")) return;

      const sessionId: string = (input as any).sessionID ?? "";
      if (!sessionId) return;

      // Inject the context window session ID into the tool arguments.
      output.args._so_session_id = sessionId;
    },
  };
};
