// so-context OpenCode plugin — auto-generated by `so-context setup`
// Tracks project watch sessions: calls ensure-watch on session start and
// unwatch on session end, passing the OpenCode session ID so the daemon can
// maintain an accurate per-session consumer list.
//
// Event shape (from opencode/src/session/session.ts):
//   session.created / session.deleted
//     properties.sessionID  — the session identifier
//     properties.info       — full Session.Info object
//     properties.info.directory — the session's working directory

import type { Plugin } from "@opencode-ai/plugin";

export const SoContextPlugin: Plugin = async ({ directory: projectDir, $ }) => {
  const binary = "{BINARY}";

  return {
    event: async ({ event }) => {
      if (
        event.type === "session.created" ||
        event.type === "session.deleted"
      ) {
        const sessionId = (event.properties as any)?.sessionID ?? "unknown";
        await $`${binary} ${cmd} ${dir} --agent opencode --session-id ${sessionId}`
          .nothrow()
          .quiet();
      }
    },
  };
};
